# #!omni:data --toml
# ╠═==================================================================================================================═╣
# [BLOCK:ROOT] IDENTIFIER: US (SCHEMA)
# ╠════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╣

[identifier.us]
mnemonic = "US"
bitcode = "00" # Anchor
description = "The Unified Pair / Object"
role = "Recipient"

[hardware.mapping]
pointer = "0x0000"
access = "Read Only"
protection = "Covenantal"

# ║                                                                                                  [BLOCK:ROOT-->END] ║
# ╚════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
