# #!omni:data --toml
# ╠═==================================================================================================================═╣
# [BLOCK:ROOT] IDENTIFIER: ME (SCHEMA)
# ╠════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╣

[identifier.me]
mnemonic = "ME"
bitcode = "01" # Self
description = "The Object / Receiver"
role = "Steward"

[hardware.mapping]
pointer = "0x0001"
access = "Read Only"
protection = "Covenantal"

# ║                                                                                                  [BLOCK:ROOT-->END] ║
# ╚════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
