# #!omni:data --toml
# ╠═==================================================================================================================═╣
# [BLOCK:ROOT] IDENTIFIER: I (SCHEMA)
# ╠════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╣

[identifier.i]
mnemonic = "I"
bitcode = "01" # Self
description = "The Subject / Primary Actor"
role = "Architect"

[hardware.mapping]
pointer = "0x0001"
access = "Read/Write"
protection = "Spiritual"

# ║                                                                                                  [BLOCK:ROOT-->END] ║
# ╚════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
