# #!omni:data --toml
# ╠═==================================================================================================================═╣
# [BLOCK:ROOT] IDENTIFIER: SHE (SCHEMA)
# ╠════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╣

[identifier.she]
mnemonic = "SHE"
bitcode = "11" # Distal
description = "The Witness / Third Party (F)"
role = "Steward"

[hardware.mapping]
pointer = "0x0004"
access = "Read Only"
protection = "Universal"

# ║                                                                                                  [BLOCK:ROOT-->END] ║
# ╚════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
