# #!omni:data --toml
# ╠═==================================================================================================================═╣
# [BLOCK:ROOT] IDENTIFIER: YOU (SCHEMA)
# ╠════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╣

[identifier.you]
mnemonic = "YOU"
bitcode = "10" # Other
description = "The Partner / Second Party"
role = "Steward"

[hardware.mapping]
pointer = "0x0002"
access = "Read/Write"
protection = "Covenantal"

# ║                                                                                                  [BLOCK:ROOT-->END] ║
# ╚════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
